"use client";

import React, { useState } from "react";
import { parseAIResumeResponse, convertAISkillsToSkillItems, ParsedAIResponse } from "@/utils/aiResumeAssistant";
import { SkillItem } from "@/types/resume";
import { Sparkles, X, AlertCircle, AlertTriangle, FileText, ArrowRight } from "lucide-react";

interface AIImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (newSummary: string, newSkills: SkillItem[]) => void;
  hasExistingData: boolean;
  onSuccessToast: () => void;
}

export function AIImportModal({
  isOpen,
  onClose,
  onImport,
  hasExistingData,
  onSuccessToast,
}: AIImportModalProps) {
  const [pastedText, setPastedText] = useState("");
  const [parseError, setParseError] = useState<string | null>(null);
  const [pendingParsedData, setPendingParsedData] = useState<ParsedAIResponse | null>(null);
  const [showOverwriteConfirm, setShowOverwriteConfirm] = useState(false);

  if (!isOpen) return null;

  const handleClose = () => {
    setPastedText("");
    setParseError(null);
    setPendingParsedData(null);
    setShowOverwriteConfirm(false);
    onClose();
  };

  const handleAttemptImport = () => {
    setParseError(null);
    if (!pastedText.trim()) {
      setParseError("Please paste your ChatGPT response first.");
      return;
    }

    const parsed = parseAIResumeResponse(pastedText);
    if (!parsed) {
      setParseError("Couldn't recognize the AI response format. Please make sure you're pasting the final response generated by ChatGPT.");
      return;
    }

    if (hasExistingData) {
      setPendingParsedData(parsed);
      setShowOverwriteConfirm(true);
    } else {
      executeImport(parsed);
    }
  };

  const executeImport = (parsed: ParsedAIResponse) => {
    const skillItems = convertAISkillsToSkillItems(parsed.technicalSkills, parsed.softSkills);
    onImport(parsed.summary, skillItems);
    onSuccessToast();
    handleClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-zinc-950/70 backdrop-blur-xs animate-fade-in">
      <div className="bg-white text-zinc-950 rounded-2xl border border-zinc-200 shadow-2xl w-full max-w-xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Modal Header */}
        <div className="bg-slate-900 text-white px-4 sm:px-6 py-3.5 sm:py-4 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <Sparkles className="w-4 h-4 sm:w-4.5 sm:h-4.5 text-emerald-400 shrink-0" />
            <div>
              <h3 className="font-bold text-sm tracking-tight text-white">Import AI Resume Content</h3>
              <p className="text-[11px] sm:text-xs text-slate-300">Paste your ChatGPT output to auto-fill Summary & Skills</p>
            </div>
          </div>
          <button 
            onClick={handleClose} 
            className="text-slate-400 hover:text-white p-1.5 rounded-lg hover:bg-slate-800 transition-colors min-h-[36px] min-w-[36px] flex items-center justify-center"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-4 sm:p-6 overflow-y-auto space-y-4 flex-1">
          {showOverwriteConfirm ? (
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 sm:p-5 text-amber-950 space-y-3">
              <div className="flex items-center gap-2 text-amber-800 font-extrabold text-sm">
                <AlertTriangle className="w-4.5 h-4.5 shrink-0 text-amber-600" />
                <span>Overwrite Confirmation Required</span>
              </div>
              <p className="text-xs text-amber-900 leading-relaxed font-medium">
                Your existing AI-supported fields will be replaced. Continue?
              </p>
              <div className="bg-white/80 p-3 rounded-lg border border-amber-200 text-xs space-y-1.5 text-zinc-800">
                <div className="font-bold text-zinc-900">Content ready to import:</div>
                {pendingParsedData?.summary && (
                  <div className="line-clamp-2 italic text-zinc-600">
                    &quot;{pendingParsedData.summary}&quot;
                  </div>
                )}
                <div className="flex flex-wrap gap-1 pt-1">
                  <span className="bg-emerald-100 text-emerald-800 text-[10px] font-bold px-2 py-0.5 rounded">
                    {pendingParsedData?.technicalSkills.length || 0} Tech Skills
                  </span>
                  <span className="bg-blue-100 text-blue-800 text-[10px] font-bold px-2 py-0.5 rounded">
                    {pendingParsedData?.softSkills.length || 0} Soft Skills
                  </span>
                </div>
              </div>
            </div>
          ) : (
            <>
              <p className="text-xs text-zinc-600 leading-relaxed">
                Paste the response generated by ChatGPT below. We&apos;ll automatically place the content into the correct resume fields.
              </p>

              {parseError && (
                <div className="bg-red-50 border border-red-200 rounded-xl p-3.5 flex items-start gap-2.5 text-xs text-red-700 animate-shake">
                  <AlertCircle className="w-4 h-4 shrink-0 text-red-600 mt-0.5" />
                  <span className="font-medium leading-relaxed">{parseError}</span>
                </div>
              )}

              <div>
                <label className="block text-xs font-extrabold text-zinc-900 mb-1.5">
                  ChatGPT Response Text
                </label>
                <textarea
                  value={pastedText}
                  onChange={(e) => {
                    setPastedText(e.target.value);
                    if (parseError) setParseError(null);
                  }}
                  rows={6}
                  placeholder="Paste your ChatGPT response here..."
                  className="w-full bg-zinc-50 border border-zinc-300 focus:border-zinc-900 focus:bg-white rounded-xl p-3 text-xs sm:text-sm text-zinc-900 placeholder:text-zinc-400 font-mono outline-none focus:ring-2 focus:ring-zinc-900 transition-all"
                />
              </div>
            </>
          )}
        </div>

        {/* Modal Actions Footer */}
        <div className="bg-zinc-100 px-4 sm:px-6 py-3.5 sm:py-4 border-t border-zinc-200 flex flex-col-reverse sm:flex-row items-stretch sm:items-center justify-between gap-2.5">
          <button
            type="button"
            onClick={handleClose}
            className="text-xs font-semibold text-zinc-600 hover:text-zinc-900 px-4 py-2.5 rounded-lg hover:bg-zinc-200 transition-colors min-h-[44px]"
          >
            Cancel
          </button>

          {showOverwriteConfirm ? (
            <button
              type="button"
              onClick={() => pendingParsedData && executeImport(pendingParsedData)}
              className="text-xs bg-amber-600 hover:bg-amber-700 text-white font-bold px-5 py-2.5 rounded-xl shadow-sm transition-all flex items-center justify-center gap-2 min-h-[44px]"
            >
              <span>Replace & Import</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button
              type="button"
              onClick={handleAttemptImport}
              className="text-xs bg-zinc-900 hover:bg-zinc-800 text-white font-bold px-6 py-2.5 rounded-xl shadow-md transition-all flex items-center justify-center gap-2 min-h-[44px]"
            >
              <FileText className="w-4 h-4 text-emerald-400" />
              <span>Import Content</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
